// Apelidos de busca (pedido do autor, 2026-09): como o achado é chamado na
// enfermaria, em sigla ou em inglês corrente. São termos SOMENTE de busca:
// nunca aparecem na interface nem no conteúdo, só aumentam o recall do
// índice. A chave é o nome exato do verbete `sinal` no conteúdo revisado.

export const APELIDOS_DE_SINAIS: Record<string, string[]> = {
  'Sinal de Blumberg': ['rebote', 'descompressão brusca dolorosa', 'DB positiva'],
  'Sinal de Giordano': ['punhopercussão lombar', 'punho percussão'],
  'Sinal do piparote': ['onda líquida da ascite'],
  'Macicez móvel': ['macicez de decúbito'],
  'Silêncio abdominal': ['RHA ausentes', 'ruídos hidroaéreos ausentes', 'peristalse ausente'],
  'Sinal de Murphy': ['parada inspiratória dolorosa'],
  'Sinal de Courvoisier': ['vesícula palpável indolor'],
  'Sinal de Jobert': ['perda da macicez hepática'],
  'Borda hepática palpável': ['hepatomegalia', 'fígado aumentado', 'fígado palpável'],
  'Turgência jugular': ['estase jugular', 'jugulares ingurgitadas'],
  'Refluxo hepatojugular (teste abdominojugular)': ['RHJ'],
  'Ictus cordis desviado ou aumentado': ['choque da ponta desviado'],
  'Levantamento em massa do precórdio (impulsão sistólica)': ['impulsão paraesternal'],
  'Ritmo de galope por B3': ['terceira bulha', 'galope ventricular'],
  'Galope atrial por B4': ['quarta bulha'],
  'Desdobramento fixo de B2': ['segunda bulha desdobrada fixa'],
  'Hipotensão ortostática': ['hipotensão postural'],
  'Déficit de pulso': ['dissociação pulso precórdio'],
  'Baqueteamento digital (hipocratismo digital)': ['clubbing', 'dedos em baqueta de tambor', 'unhas em vidro de relógio'],
  'Edema com cacifo (sinal de Godet)': ['fóvea'],
  'Turgor cutâneo diminuído (prega lenta)': ['sinal da prega'],
  'Palidez da rima conjuntival': ['mucosas hipocoradas', 'mucosas descoradas'],
  'Manchas hemorrágicas (petéquias, víbices e equimoses)': ['púrpura'],
  'Tiragem': ['retração intercostal', 'retração de fúrcula'],
  'Sibilos': ['chiado', 'chieira', 'wheezing'],
  'Estertores finos (crepitantes)': ['crepitações', 'estertores em velcro'],
  'Estridor': ['cornagem'],
  'Egofonia': ['voz caprina'],
  'Sopro tubário (som brônquico fora do lugar)': ['respiração soprosa'],
  'Frêmito toracovocal alterado': ['FTV'],
  'Enfisema subcutâneo': ['crepitação subcutânea'],
  'Movimento abdominal paradoxal': ['respiração paradoxal'],
  'Respiração de Cheyne-Stokes': ['respiração periódica'],
  'Sinal de Babinski': ['cutâneo-plantar em extensão', 'reflexo cutâneo plantar em extensão'],
  'Clônus do pé e da rótula': ['clono'],
  'Sinal da roda denteada': ['rigidez em roda dentada'],
  'Fenômeno do canivete': ['espasticidade em canivete'],
  'Desvio em pronação (braços estendidos)': ['prova dos braços estendidos', 'pronator drift'],
  'Defeito pupilar aferente relativo (pupila de Marcus Gunn)': ['DPAR', 'swinging flashlight'],
  'Teste do impulso cefálico (manobra de Halmagyi)': ['head impulse test'],
  'Manobra de Fukuda': ['Unterberger'],
  'Marcha vestibular (em estrela)': ['Babinski-Weil'],
  'Marcha talonante (atáxica sensitiva)': ['marcha tabética', 'marcha calcaneante'],
  'Marcha atáxica cerebelar (do ébrio)': ['marcha ebriosa'],
  'Marcha ceifante (hemiplégica)': ['marcha helicópode'],
  'Marcha parkinsoniana': ['marcha festinante'],
  'Sinal de Lasègue e elevação da perna estendida': ['straight leg raise'],
  'Teste do aperto da panturrilha': ['Thompson', 'Simmonds', 'Simmonds-Thompson'],
  'Adução cruzada (teste do cachecol)': ['scarf test'],
  'Teste de Jobe (lata vazia)': ['empty can'],
  'Teste do pivot shift': ['ressalto rotatório'],
  'Exoftalmia': ['proptose'],
  'Bócio': ['tireoide aumentada'],
  'Baço palpável (esplenomegalia)': ['baço aumentado'],
  'Nódulo de Virchow (linfonodo supraclavicular)': ['gânglio de Troisier'],
  'Úlcera venosa': ['úlcera de estase'],
  'Phlegmasia alba e cerulea dolens': ['flegmasia'],
  'Sinais da torção testicular (Brunzel, Angell e Ger)': ['escroto agudo'],
  'Reflexo de Cushing': ['tríade de Cushing'],
  'Reflexo de Moro': ['reflexo do abraço'],
  'Manobra de Sabouraud (tração dos cabelos)': ['teste de tração capilar'],
  'Método de avaliação de confusão (CAM) positivo': ['confusion assessment method'],
};
